show desktop warning if backup of source hosts failed

diff --git a/templates/backup.sh.j2 b/templates/backup.sh.j2
--- a/templates/backup.sh.j2
+++ b/templates/backup.sh.j2
@@ -1,10 +1,20 @@
 #!/bin/bash
+errors=
 notify-send "Starting backup"
 {% for host in groups[backup_slave_group_name] %}
 {% for source in hostvars[host][backup_slave_sources_name] %}
 echo '===============================================' >> /var/log/backup/{{ host }}.log
 date -Is  >> /var/log/backup/{{ host }}.log
 rsync --stats {{ backup_master_rsync_opts | default(source.rsync_opts) }} {{ source.user }}@{{ hostvars[host]['ansible_host'] }}:{{ source.path }} {{ backup_device.path }}/{{ host }} &>> /var/log/backup/{{ host }}.log
+if [ ! $? -eq 0 ]
+then
+    error="${error}{{ host }} "
+fi
 {% endfor %}
 {% endfor %}
-notify-send -c "transfer.complete" "Backup finished, please remove backup device"
+if [ -z "$error" ]
+then
+    notify-send -c "transfer.complete" "Backup finished, please remove backup device" --icon=dialog-information
+else
+    notify-send -c "transfer.complete" "Backup finished with errors for these hosts: ${error}" --icon=dialog-warning
+fi
